#!/usr/bin/env bash
# Stop AND PostToolUse (matcher: Edit|Write) — live status board.
#
# Regenerates STATUS.md at the project root, a one-screen view of where the
# task board stands. ONLY runs if the project already has TASKS.md; otherwise
# it does nothing (no STATUS.md is ever created for a non-mogger project).
#
# STATUS.md shows:
#   - done / open task counts, the next 3 open tasks
#   - any "BLOCKED:" line and the "## Status:" line from TASKS.md
#   - last 5 files touched (from `git status --porcelain`, newest first)
#   - last checkpoint / test marker time (from .claude/state/, if present)
#   - cost so far, from .claude/state/cost.json (written by cost-cap.sh; an
#     ESTIMATE from token counts x published rates) and any budget warning
#   - a timestamp
#
# Guarantees: ALWAYS exits 0 (never blocks anything, fails open on any
# error). Fast: pure bash + one `git status`, no python. Atomic write (temp
# file + mv). If nothing changed except the timestamp, the file is not
# rewritten, so its mtime stays put.
source "$(dirname "$0")/lib.sh" 2>/dev/null

[ -t 0 ] || cat >/dev/null 2>&1

_mtime() {  # file -> epoch seconds (GNU stat, then BSD stat)
  stat -c %Y "$1" 2>/dev/null || stat -f %m "$1" 2>/dev/null || printf 0
}
_fmt() {  # epoch -> UTC timestamp
  date -u -d "@$1" +"%Y-%m-%d %H:%M:%SZ" 2>/dev/null || date -u -r "$1" +"%Y-%m-%d %H:%M:%SZ" 2>/dev/null || printf '%s' "$1"
}

build_status() {
  local done_n open_n
  done_n=$(grep -c '^[[:space:]]*- \[[xX]\]' TASKS.md 2>/dev/null); done_n=${done_n:-0}
  open_n=$(grep -c '^[[:space:]]*- \[ \]' TASKS.md 2>/dev/null); open_n=${open_n:-0}

  echo "# STATUS"
  echo
  echo "_Generated by mogger (update-status.sh). Do not edit; it is rewritten automatically._"
  echo
  echo "## Tasks"
  echo "- $done_n done, $open_n open"
  local st
  st=$(grep -m1 -iE '^##[[:space:]]+Status:' TASKS.md 2>/dev/null)
  [ -n "$st" ] && echo "- ${st#\#\# }"
  echo
  echo "## Next up"
  local nxt
  nxt=$(grep -E '^[[:space:]]*- \[ \]' TASKS.md 2>/dev/null | head -3 | sed 's/^[[:space:]]*- \[ \] //')
  if [ -n "$nxt" ]; then printf '%s\n' "$nxt" | sed 's/^/- /'; else echo "- (nothing open)"; fi

  local blk
  blk=$(grep -iE '^[[:space:]]*BLOCKED:' TASKS.md 2>/dev/null | sed 's/^[[:space:]]*//')
  if [ -n "$blk" ]; then
    echo
    echo "## Blocked"
    printf '%s\n' "$blk" | sed 's/^/- /'
  fi

  echo
  echo "## Last 5 files touched"
  local files="" line f m
  if git rev-parse --git-dir >/dev/null 2>&1; then
    while IFS= read -r line; do
      f=${line:3}
      case "$f" in *" -> "*) f=${f##* -> } ;; esac
      f=${f#\"}; f=${f%\"}
      case "$f" in STATUS.md|.claude/*) continue ;; esac
      [ -e "$f" ] || continue
      m=$(_mtime "$f")
      files="${files}${m} ${f}
"
    done <<EOF2
$(git status --porcelain 2>/dev/null)
EOF2
  fi
  if [ -n "$files" ]; then
    printf '%s' "$files" | sort -rn | head -5 | sed 's/^[0-9]* /- /'
  else
    echo "- (no uncommitted changes)"
  fi

  echo
  echo "## Markers"
  local best=0 bestf="" mk t
  for mk in .claude/state/last_test_result.json .claude/state/*checkpoint*; do
    [ -f "$mk" ] || continue
    t=$(_mtime "$mk")
    if [ "$t" -gt "$best" ]; then best=$t; bestf=$mk; fi
  done
  if [ -n "$bestf" ]; then echo "- last checkpoint/test marker: $(_fmt "$best") ($(basename "$bestf"))"
  else echo "- no checkpoint/test marker yet"; fi

  echo
  echo "## Cost (estimate)"
  local cj=.claude/state/cost.json
  if [ -f "$cj" ]; then
    local sp bu pc wn
    sp=$(sed -n 's/.*"spent_usd": *\([0-9.]*\).*/\1/p' "$cj" | head -1)
    bu=$(sed -n 's/.*"budget_usd": *\([0-9.]*\).*/\1/p' "$cj" | head -1)
    pc=$(sed -n 's/.*"pct": *\([0-9.]*\).*/\1/p' "$cj" | head -1)
    wn=$(sed -n 's/.*"warning": *"\([^"]*\)".*/\1/p' "$cj" | head -1)
    echo "- about \$${sp:-?} spent of \$${bu:-?} budget (${pc:-?}%), estimated from token counts x published rates"
    [ -n "$wn" ] && echo "- WARNING: $wn"
  else
    echo "- not tracked (set MOGGER_BUDGET_USD to turn on the cost cap)"
  fi
}

main() {
  [ -f TASKS.md ] || return 0
  local body new old tmp
  body=$(build_status) || return 0
  [ -n "$body" ] || return 0
  if [ -f STATUS.md ]; then
    old=$(grep -v '^_Updated:' STATUS.md 2>/dev/null)
    [ "$old" = "$body" ] && return 0
  fi
  tmp="STATUS.md.tmp.$$"
  {
    printf '%s\n' "$body"
    echo
    echo "_Updated: $(date -u +"%Y-%m-%d %H:%M:%SZ")_"
  } > "$tmp" 2>/dev/null && mv -f "$tmp" STATUS.md 2>/dev/null
  rm -f "$tmp" 2>/dev/null
  return 0
}

main >/dev/null 2>&1 || true
exit 0
